### ISSUE TITLE
select and submit an answer

### ISSUE THREAD

**Issue by nomeski80** [nomeski80/My-First-Agile-Project#1]
**In order to** provide my opinion with regards to a certain running topic or event as a **user** I can select and submit an answer from the poll. 
+ write a choice of 4 options for the poll
+ add checkboxes for the user to click on

# Tasks
- [ ] Design the checkboxes for the user to select
- [ ]  Create the HTML and CSS for the input forms
- [ ]  Add in the functionality for the form and where the information will be sent to the customer
